<a href="https://colab.research.google.com/github/KAMBLE/Tensorflow/blob/main/code_1st_tensorflow_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Fundametals OF Tensorflow**

## constant 

In [ ]:
import tensorflow as tf 
import numpy as np
print(tf.__version__)

2.4.1


In [ ]:
scaler = tf.constant(7)
scaler

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
scaler.ndim

0

In [ ]:
vector = tf.constant([10,20])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 20], dtype=int32)>

In [ ]:
vector.ndim

1

In [ ]:
matrix = tf.constant([[10,7],
                     [7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [ ]:
matrix.ndim

2

In [ ]:
#specify datat type 
another_matrix = tf.constant([[10.,7.],
                     [7.,10.],
                     [10.,20.]],dtype=tf.float16)
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 7., 10.],
       [10., 20.]], dtype=float16)>

In [ ]:
another_matrix.ndim

2

In [ ]:
tensor = tf.constant([[[1,2,3],
                       [4,5,6]],
                      [[7,8,9],
                       [10,11,12]],
                      [[13,14,15],
                       [16,17,18]]
                       ])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [ ]:
tensor.ndim

3

## variable 

In [ ]:
chg_tensor = tf.Variable([10,7])
nch_tensor = tf.constant([10,7])
chg_var,nch_var 

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [ ]:
chg_tensor[0].assign(7)
chg_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [ ]:
nch_tensor[0].assign(7)

AttributeError: ignored

## random variable

In [ ]:
random_1 = tf.random.Generator.from_seed(42)
random_1 = random_1.normal(shape=(3,2))
random_1

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

### shuffle order of elemtns 

In [ ]:
not_shuffled = tf.constant([[1,2],
                             [3,4],
                             [5,6]])
not_shuffled.ndim


2

In [ ]:
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[3, 4],
       [1, 2],
       [5, 6]], dtype=int32)>

In [ ]:
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[5, 6],
       [3, 4],
       [1, 2]], dtype=int32)>

### create tensor with numpy
#### main diff between numpy aaray and tensorflow tensor is that tensor runs faster on GPU than numpy !

In [ ]:
tf.ones([10,7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [ ]:
tf.zeros([10,7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>

In [ ]:
import numpy as np
numpy_A = np.arange(1,25,dtype=np.int32)
numpy_A 

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [ ]:
A = tf.constant(numpy_A)
A

<tf.Tensor: shape=(24,), dtype=int32, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)>

In [ ]:
B = tf.constant(numpy_A,shape=[2,3,4])
B

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]], dtype=int32)>

In [ ]:
C = tf.constant(numpy_A,shape=[3,8])
C

<tf.Tensor: shape=(3, 8), dtype=int32, numpy=
array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22, 23, 24]], dtype=int32)>

###Getting information from tensors

In [ ]:
rank_4_tensor = tf.zeros(shape=(2,3,4,5))
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
print("data type of tensor ",rank_4_tensor.dtype)
print("no od dimension(rank) ",rank_4_tensor.ndim)
print("shape of tensor ",rank_4_tensor.shape)
print("elemnts along the 0 axis ",rank_4_tensor.shape[0])
print("elemts along last axis ",rank_4_tensor.shape[-1])
print("total elemns in tesnor ",tf.size(rank_4_tensor))
print("total elemns in tesnor ",tf.size(rank_4_tensor).numpy())

data type of tensor  <dtype: 'float32'>
no od dimension(rank)  4
shape of tensor  (2, 3, 4, 5)
elemnts along the 0 axis  2
elemts along last axis  5
total elemns in tesnor  tf.Tensor(120, shape=(), dtype=int32)
total elemns in tesnor  120


## indexing tensor 

In [ ]:
# get first  2 elements of each dimension
rank_4_tensor[:2,:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [ ]:
# get 1st elemt from each dimension except last one 
rank_4_tensor[:1,:1,:1]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

### tebsor operations

In [ ]:
tensor = tf.constant([[10,20],[3,4]])
tensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 30],
       [13, 14]], dtype=int32)>

In [ ]:
tensor*10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100, 200],
       [ 30,  40]], dtype=int32)>

In [ ]:
tensor-10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, 10],
       [-7, -6]], dtype=int32)>

In [ ]:
tf.multiply(tensor,10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100, 200],
       [ 30,  40]], dtype=int32)>

In [ ]:
tf.subtract(tensor,10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, 10],
       [-7, -6]], dtype=int32)>

In [ ]:
tf.matmul(tensor,tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[160, 280],
       [ 42,  76]], dtype=int32)>

In [ ]:
tensor*tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100, 400],
       [  9,  16]], dtype=int32)>

In [ ]:
tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[160, 280],
       [ 42,  76]], dtype=int32)>

###changing dattype of tensor

In [ ]:
A = tf.constant([1.9,2.3])
A.dtype

tf.float32

In [ ]:
B =  tf.constant([7,10])
B.dtype

tf.int32

In [ ]:
#float32 to float16
D = tf.cast(A,dtype=tf.float16)
D

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.9, 2.3], dtype=float16)>

In [ ]:
E = tf.cast(B,dtype=tf.int16)
E

<tf.Tensor: shape=(2,), dtype=int16, numpy=array([ 7, 10], dtype=int16)>

###Aggregating tensord
* min
* max
* mean of tensor
* sum of tensor

In [ ]:
import numpy as np
e = tf.constant(np.random.randint(0,100,size=50))
e

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([ 2, 69, 36,  8, 20, 24, 48, 19, 70, 79, 14, 10, 20, 89, 71,  3, 16,
       74, 74, 63, 49, 13, 16, 80, 51, 55,  9,  1,  0, 35,  9, 86,  8, 46,
        9, 74, 11, 37, 46, 79, 71, 13, 54, 73, 24, 96, 60, 75, 33, 27])>

In [ ]:
tf.size(e),e.shape,e.ndim

(<tf.Tensor: shape=(), dtype=int32, numpy=50>, TensorShape([50]), 1)

In [ ]:
tf.reduce_min(e)

<tf.Tensor: shape=(), dtype=int64, numpy=0>

In [ ]:
tf.reduce_max(e)

<tf.Tensor: shape=(), dtype=int64, numpy=96>

In [ ]:
tf.reduce_mean(e)

<tf.Tensor: shape=(), dtype=int64, numpy=40>

In [ ]:
tf.reduce_sum(e)

<tf.Tensor: shape=(), dtype=int64, numpy=2049>

In [ ]:
import tensorflow_probability as tfp
tfp.stats.variance(e)

<tf.Tensor: shape=(), dtype=int64, numpy=826>

In [ ]:
tfp.stats.variance(e)

###find positional min , max

In [ ]:
tf.random.set_seed(50)
f = tf.random.uniform(shape=[50])
f

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.94196117, 0.1697309 , 0.5064962 , 0.27598453, 0.899318  ,
       0.4486513 , 0.43584716, 0.71771336, 0.85751176, 0.12559032,
       0.0875535 , 0.85261035, 0.17349517, 0.31913245, 0.4845121 ,
       0.5540675 , 0.6620537 , 0.20845115, 0.43225408, 0.9061552 ,
       0.52628434, 0.30039036, 0.5774927 , 0.5814352 , 0.7920803 ,
       0.396855  , 0.02649951, 0.43159127, 0.11073196, 0.5804652 ,
       0.83437836, 0.17531359, 0.5109179 , 0.91586626, 0.21497321,
       0.41104853, 0.7946409 , 0.30716085, 0.3172475 , 0.15829349,
       0.5417241 , 0.49205697, 0.19820452, 0.25472498, 0.2333138 ,
       0.2071842 , 0.5443722 , 0.01052618, 0.57121956, 0.33880603],
      dtype=float32)>

In [ ]:
#find po(sitional max
tf.argmax(f)

<tf.Tensor: shape=(), dtype=int64, numpy=0>

In [ ]:
f[tf.argmax(f)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.94196117>

In [ ]:
tf.argmin(f),f[tf.argmin(f)]

(<tf.Tensor: shape=(), dtype=int64, numpy=47>,
 <tf.Tensor: shape=(), dtype=float32, numpy=0.01052618>)

#### squeezing tensor

In [ ]:
tf.random.set_seed(56)
g = tf.constant(tf.random.uniform(shape=[50]),shape=(1,1,1,1,50))
g

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.94518936, 0.05931079, 0.8201647 , 0.51676476, 0.66400445,
           0.17557847, 0.7123766 , 0.9893799 , 0.78432536, 0.24566388,
           0.5357388 , 0.93536043, 0.8706596 , 0.69577885, 0.64920294,
           0.9529476 , 0.09277964, 0.24157453, 0.77892303, 0.08109808,
           0.96769845, 0.7423785 , 0.04304242, 0.61586297, 0.42966914,
           0.5100548 , 0.830451  , 0.287264  , 0.49771273, 0.03829527,
           0.21342623, 0.9617338 , 0.6340543 , 0.37643707, 0.37555397,
           0.79713476, 0.10297978, 0.27411532, 0.7368487 , 0.56859875,
           0.7003217 , 0.8839742 , 0.45640063, 0.651564  , 0.71889424,
           0.5103525 , 0.919139  , 0.47225773, 0.6199446 , 0.22999322]]]]],
      dtype=float32)>

In [ ]:
g_sqz = tf.squeeze(g)
g_sqz

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.94518936, 0.05931079, 0.8201647 , 0.51676476, 0.66400445,
       0.17557847, 0.7123766 , 0.9893799 , 0.78432536, 0.24566388,
       0.5357388 , 0.93536043, 0.8706596 , 0.69577885, 0.64920294,
       0.9529476 , 0.09277964, 0.24157453, 0.77892303, 0.08109808,
       0.96769845, 0.7423785 , 0.04304242, 0.61586297, 0.42966914,
       0.5100548 , 0.830451  , 0.287264  , 0.49771273, 0.03829527,
       0.21342623, 0.9617338 , 0.6340543 , 0.37643707, 0.37555397,
       0.79713476, 0.10297978, 0.27411532, 0.7368487 , 0.56859875,
       0.7003217 , 0.8839742 , 0.45640063, 0.651564  , 0.71889424,
       0.5103525 , 0.919139  , 0.47225773, 0.6199446 , 0.22999322],
      dtype=float32)>

###one hot encoding

In [ ]:
some_list = [0,1,2,3,4]
tf.one_hot(some_list,4)

<tf.Tensor: shape=(5, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]], dtype=float32)>

###squaring,log 

In [ ]:
h = tf.range(1,10)
h

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [ ]:
tf.square(h)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [ ]:
tf.sqrt(tf.cast(h,dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.99999994, 1.4142134 , 1.7320508 , 1.9999999 , 2.236068  ,
       2.4494896 , 2.6457512 , 2.8284268 , 3.        ], dtype=float32)>

In [ ]:
tf.math.log(tf.cast(h,dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

In [ ]:
###tensor & numpy 

###tensor & numpy 

In [ ]:
# tensor form numpy array

j = tf.constant(np.array([2.,3,10]))
j

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 2.,  3., 10.])>

In [ ]:
#convert back to array
np.array(j)


array([ 2.,  3., 10.])

In [ ]:
j.numpy()

array([ 2.,  3., 10.])